[mgr]
prepend_keymap = [
  # Exit to current directory (explicitly write cwd)
  { on = [ "S" ], run = [ "cd --interactive", "quit --cwd" ], desc = "Quit to CWD" },
  # Normal quit (don't write cwd)
  { on = [ "q" ], run = "close", desc = "Quit" },
]
