[manager]
prepend_keymap = [
  # Change open_with to 'r' (like rifle in ranger)
  { on = [ "r" ], run = "open", desc = "Open with" },
  
  # Change sort to 'o'
  { on = [ "o", "m" ], run = "sort modified --dir-first", desc = "Sort by mtime" },
  { on = [ "o", "M" ], run = "sort modified --reverse --dir-first", desc = "Sort by mtime (reverse)" },
  { on = [ "o", "c" ], run = "sort created --dir-first", desc = "Sort by ctime" },
  { on = [ "o", "C" ], run = "sort created --reverse --dir-first", desc = "Sort by ctime (reverse)" },
  { on = [ "o", "e" ], run = "sort extension --dir-first", desc = "Sort by extension" },
  { on = [ "o", "E" ], run = "sort extension --reverse --dir-first", desc = "Sort by extension (reverse)" },
  { on = [ "o", "a" ], run = "sort alphabetical --dir-first", desc = "Sort by name" },
  { on = [ "o", "A" ], run = "sort alphabetical --reverse --dir-first", desc = "Sort by name (reverse)" },
  { on = [ "o", "s" ], run = "sort size --dir-first", desc = "Sort by size" },
  { on = [ "o", "S" ], run = "sort size --reverse --dir-first", desc = "Sort by size (reverse)" },
]
