[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "application/json", use = "edit" },
  { mime = "inode/x-empty", use = "edit" },
  { name = "*.conf", use = "edit" },
  { name = "*.css", use = "edit" },
  { name = "*.nix", use = "edit" },
  { name = "config", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.yaml", use = "edit" },
  { name = "*.yml", use = "edit" },
]
